name: Test Action
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test_linux:
    name: Test action on linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        name: Test the action.
        with:
          version: 2201.1.1
      - run: bal version
      - run: bal run hello.bal
  test_windows:
    name: Test action on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        name: Test the action.
        with:
          version: 2201.1.1
      - run: bal version
      - run: bal run hello.bal
  test_macos:
    name: Test action on MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        name: Test the action.
        with:
          version: 2201.1.1
      - run: bal version
      - run: bal run hello.bal

